### ISSUE TITLE
Добавить лицензию

### ISSUE THREAD

**Issue by YPermitin** [rsyuzyov/work-on-linux#3]
Пожалуйста добавьте лицензию на материалы репозитория.

P.S. Материал интересный, спасибо Вам :)

**Comment by rsyuzyov** [comment]
Ой, хто здесь ?! :)
[Готово!](https://github.com/rsyuzyov/work-on-linux/blob/master/LICENSE)

**Comment by YPermitin** [comment]
@rsyuzyov Спасибо! :)
